# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(884, 974)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 20, 801, 861))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textBrowser_Overview = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_Overview.setGeometry(QtCore.QRect(30, 20, 721, 241))
        self.textBrowser_Overview.setObjectName("textBrowser_Overview")
        self.comboBox_ownRobi = QtWidgets.QComboBox(self.tab)
        self.comboBox_ownRobi.setGeometry(QtCore.QRect(100, 530, 191, 61))
        self.comboBox_ownRobi.setObjectName("comboBox_ownRobi")
        self.labelownRobi = QtWidgets.QLabel(self.tab)
        self.labelownRobi.setGeometry(QtCore.QRect(100, 510, 181, 16))
        self.labelownRobi.setObjectName("labelownRobi")
        self.start_pushButton = QtWidgets.QPushButton(self.tab)
        self.start_pushButton.setGeometry(QtCore.QRect(190, 660, 381, 161))
        self.start_pushButton.setObjectName("start_pushButton")
        self.error_textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.error_textBrowser.setGeometry(QtCore.QRect(50, 840, 641, 51))
        self.error_textBrowser.setObjectName("error_textBrowser")
        self.checkBox_ManualMode = QtWidgets.QCheckBox(self.tab)
        self.checkBox_ManualMode.setGeometry(QtCore.QRect(590, 800, 121, 21))
        self.checkBox_ManualMode.setObjectName("checkBox_ManualMode")
        self.spoofing_checkBox = QtWidgets.QCheckBox(self.tab)
        self.spoofing_checkBox.setGeometry(QtCore.QRect(590, 770, 83, 21))
        self.spoofing_checkBox.setObjectName("spoofing_checkBox")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textEdit_log = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_log.setGeometry(QtCore.QRect(20, 40, 751, 851))
        self.textEdit_log.setObjectName("textEdit_log")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame = QtWidgets.QFrame(self.tab_3)
        self.frame.setGeometry(QtCore.QRect(10, 10, 651, 411))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.manual_control = QtWidgets.QLabel(self.frame)
        self.manual_control.setGeometry(QtCore.QRect(20, 10, 211, 41))
        self.manual_control.setObjectName("manual_control")
        self.pushButton_undock = QtWidgets.QPushButton(self.frame)
        self.pushButton_undock.setGeometry(QtCore.QRect(420, 10, 101, 71))
        self.pushButton_undock.setStyleSheet(
            "QPushButton {\n"
            "    /* Base Appearance */\n"
            "    background-color: #cccccc; /* Changed to Light Grey */\n"
            "    color: #333333; /* Changed text color to dark grey for contrast */\n"
            "    border: 1px solid #999999; /* Darker border for definition */\n"
            "    border-radius: 4px; \n"
            "    padding: 6px 12px; \n"
            "    \n"
            "    /* Font and Symbol Styling */\n"
            "    font-family: Arial, sans-serif; \n"
            "    font-size: 12pt; \n"
            "    font-weight: bold;\n"
            "}"
        )
        self.pushButton_undock.setObjectName("pushButton_undock")
        self.pushButton_dock = QtWidgets.QPushButton(self.frame)
        self.pushButton_dock.setGeometry(QtCore.QRect(530, 10, 111, 71))
        self.pushButton_dock.setStyleSheet(
            "QPushButton {\n"
            "    /* Base Appearance */\n"
            "    background-color: #cccccc; /* Changed to Light Grey */\n"
            "    color: #333333; /* Changed text color to dark grey for contrast */\n"
            "    border: 1px solid #999999; /* Darker border for definition */\n"
            "    border-radius: 4px; \n"
            "    padding: 6px 12px; \n"
            "    \n"
            "    /* Font and Symbol Styling */\n"
            "    font-family: Arial, sans-serif; \n"
            "    font-size: 12pt; \n"
            "    font-weight: bold;\n"
            "}"
        )
        self.pushButton_dock.setObjectName("pushButton_dock")
        self.pushButton_backw = QtWidgets.QPushButton(self.frame)
        self.pushButton_backw.setGeometry(QtCore.QRect(280, 230, 80, 50))
        self.pushButton_backw.setStyleSheet(
            "QPushButton {\n"
            "    /* Base Appearance */\n"
            "    background-color: #007bff; /* Standard Blue */\n"
            "    color: white; \n"
            "    border: 1px solid #0056b3;\n"
            "    border-radius: 4px; /* Slightly rounded corners */\n"
            "    padding: 6px 12px; /* Top/Bottom padding, Left/Right padding */\n"
            "    \n"
            "    /* Font and Symbol Styling */\n"
            "    font-family: Arial, sans-serif; /* Ensure a clean font for the arrow symbol */\n"
            "    font-size: 12pt; /* Larger size for the arrow symbol */\n"
            "    font-weight: bold;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #0056b3; /* Darker blue on hover */\n"
            "    border-color: #004494;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: #004494; /* Even darker blue when pressed */\n"
            "    border-style: inset; /* Simulates a push down effect */\n"
            "    padding: 7px 11px 5px 13px; /* Shifts content slightly */\n"
            "}\n"
            "\n"
            "QPushButton:disabled {\n"
            "    background-color: #80a0c0;\n"
            "    color: #cccccc;\n"
            "    border-color: #6080a0;\n"
            "}"
        )
        self.pushButton_backw.setObjectName("pushButton_backw")
        self.pushButton_right = QtWidgets.QPushButton(self.frame)
        self.pushButton_right.setGeometry(QtCore.QRect(370, 170, 80, 50))
        self.pushButton_right.setStyleSheet(
            "QPushButton {\n"
            "    /* Base Appearance */\n"
            "    background-color: #007bff; /* Standard Blue */\n"
            "    color: white; \n"
            "    border: 1px solid #0056b3;\n"
            "    border-radius: 4px; /* Slightly rounded corners */\n"
            "    padding: 6px 12px; /* Top/Bottom padding, Left/Right padding */\n"
            "    \n"
            "    /* Font and Symbol Styling */\n"
            "    font-family: Arial, sans-serif; /* Ensure a clean font for the arrow symbol */\n"
            "    font-size: 12pt; /* Larger size for the arrow symbol */\n"
            "    font-weight: bold;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #0056b3; /* Darker blue on hover */\n"
            "    border-color: #004494;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: #004494; /* Even darker blue when pressed */\n"
            "    border-style: inset; /* Simulates a push down effect */\n"
            "    padding: 7px 11px 5px 13px; /* Shifts content slightly */\n"
            "}\n"
            "\n"
            "QPushButton:disabled {\n"
            "    background-color: #80a0c0;\n"
            "    color: #cccccc;\n"
            "    border-color: #6080a0;\n"
            "}"
        )
        self.pushButton_right.setObjectName("pushButton_right")
        self.pushButton_stopdrive = QtWidgets.QPushButton(self.frame)
        self.pushButton_stopdrive.setGeometry(QtCore.QRect(280, 170, 80, 50))
        self.pushButton_stopdrive.setStyleSheet(
            "QPushButton {\n"
            "    /* Base Appearance */\n"
            "    background-color: #007bff; /* Standard Blue */\n"
            "    color: white; \n"
            "    border: 1px solid #0056b3;\n"
            "    border-radius: 4px; /* Slightly rounded corners */\n"
            "    padding: 6px 12px; /* Top/Bottom padding, Left/Right padding */\n"
            "    \n"
            "    /* Font and Symbol Styling */\n"
            "    font-family: Arial, sans-serif; /* Ensure a clean font for the arrow symbol */\n"
            "    font-size: 12pt; /* Larger size for the arrow symbol */\n"
            "    font-weight: bold;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #0056b3; /* Darker blue on hover */\n"
            "    border-color: #004494;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: #004494; /* Even darker blue when pressed */\n"
            "    border-style: inset; /* Simulates a push down effect */\n"
            "    padding: 7px 11px 5px 13px; /* Shifts content slightly */\n"
            "}\n"
            "\n"
            "QPushButton:disabled {\n"
            "    background-color: #80a0c0;\n"
            "    color: #cccccc;\n"
            "    border-color: #6080a0;\n"
            "}"
        )
        self.pushButton_stopdrive.setObjectName("pushButton_stopdrive")
        self.pushButton_left = QtWidgets.QPushButton(self.frame)
        self.pushButton_left.setGeometry(QtCore.QRect(190, 170, 80, 50))
        self.pushButton_left.setStyleSheet(
            "QPushButton {\n"
            "    /* Base Appearance */\n"
            "    background-color: #007bff; /* Standard Blue */\n"
            "    color: white; \n"
            "    border: 1px solid #0056b3;\n"
            "    border-radius: 4px; /* Slightly rounded corners */\n"
            "    padding: 6px 12px; /* Top/Bottom padding, Left/Right padding */\n"
            "    \n"
            "    /* Font and Symbol Styling */\n"
            "    font-family: Arial, sans-serif; /* Ensure a clean font for the arrow symbol */\n"
            "    font-size: 12pt; /* Larger size for the arrow symbol */\n"
            "    font-weight: bold;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #0056b3; /* Darker blue on hover */\n"
            "    border-color: #004494;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: #004494; /* Even darker blue when pressed */\n"
            "    border-style: inset; /* Simulates a push down effect */\n"
            "    padding: 7px 11px 5px 13px; /* Shifts content slightly */\n"
            "}\n"
            "\n"
            "QPushButton:disabled {\n"
            "    background-color: #80a0c0;\n"
            "    color: #cccccc;\n"
            "    border-color: #6080a0;\n"
            "}"
        )
        self.pushButton_left.setObjectName("pushButton_left")
        self.pushButton_fwd = QtWidgets.QPushButton(self.frame)
        self.pushButton_fwd.setGeometry(QtCore.QRect(280, 110, 80, 50))
        self.pushButton_fwd.setStyleSheet(
            "QPushButton {\n"
            "    /* Base Appearance */\n"
            "    background-color: #007bff; /* Standard Blue */\n"
            "    color: white; \n"
            "    border: 1px solid #0056b3;\n"
            "    border-radius: 4px; /* Slightly rounded corners */\n"
            "    padding: 6px 12px; /* Top/Bottom padding, Left/Right padding */\n"
            "    \n"
            "    /* Font and Symbol Styling */\n"
            "    font-family: Arial, sans-serif; /* Ensure a clean font for the arrow symbol */\n"
            "    font-size: 12pt; /* Larger size for the arrow symbol */\n"
            "    font-weight: bold;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background-color: #0056b3; /* Darker blue on hover */\n"
            "    border-color: #004494;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background-color: #004494; /* Even darker blue when pressed */\n"
            "    border-style: inset; /* Simulates a push down effect */\n"
            "    padding: 7px 11px 5px 13px; /* Shifts content slightly */\n"
            "}\n"
            "\n"
            "QPushButton:disabled {\n"
            "    background-color: #80a0c0;\n"
            "    color: #cccccc;\n"
            "    border-color: #6080a0;\n"
            "}"
        )
        self.pushButton_fwd.setObjectName("pushButton_fwd")
        self.horizontalSlider_velo = QtWidgets.QSlider(self.frame)
        self.horizontalSlider_velo.setGeometry(QtCore.QRect(210, 320, 221, 71))
        self.horizontalSlider_velo.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_velo.setObjectName("horizontalSlider_velo")
        self.Speed_Label = QtWidgets.QLabel(self.frame)
        self.Speed_Label.setGeometry(QtCore.QRect(300, 320, 57, 15))
        self.Speed_Label.setObjectName("Speed_Label")
        self.pushButton_Stop = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_Stop.setGeometry(QtCore.QRect(690, 320, 80, 80))
        self.pushButton_Stop.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 50px;\n"
            "    background-color: #ff0000;\n"
            "    color: white;\n"
            "    border: 5px solid #a30000;\n"
            "    font-size: 12px;\n"
            "    font-weight: bold;\n"
            "}\n"
            "/* Selectors for :hover and :pressed are necessary but secondary */\n"
            "QPushButton:hover {\n"
            "    background-color: #e60000; \n"
            "}\n"
            "QPushButton:pressed {\n"
            "    background-color: #8c0000;\n"
            "    border: 3px solid #660000;\n"
            "    padding-top: 5px; \n"
            "    padding-left: 5px;\n"
            "}"
        )
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.frame_2 = QtWidgets.QFrame(self.tab_3)
        self.frame_2.setGeometry(QtCore.QRect(10, 430, 651, 341))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.manual_control_3 = QtWidgets.QLabel(self.frame_2)
        self.manual_control_3.setGeometry(QtCore.QRect(20, 10, 211, 41))
        self.manual_control_3.setObjectName("manual_control_3")
        self.pushButton_stop_nav2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_stop_nav2.setGeometry(QtCore.QRect(330, 240, 221, 71))
        self.pushButton_stop_nav2.setStyleSheet(
            "QPushButton {\n"
            "    /* Base Appearance */\n"
            "    background-color: #cccccc; /* Changed to Light Grey */\n"
            "    color: #333333; /* Changed text color to dark grey for contrast */\n"
            "    border: 1px solid #999999; /* Darker border for definition */\n"
            "    border-radius: 4px; \n"
            "    padding: 6px 12px; \n"
            "    \n"
            "    /* Font and Symbol Styling */\n"
            "    font-family: Arial, sans-serif; \n"
            "    font-size: 12pt; \n"
            "    font-weight: bold;\n"
            "}"
        )
        self.pushButton_stop_nav2.setObjectName("pushButton_stop_nav2")
        self.pushButton_start_nav2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_start_nav2.setGeometry(QtCore.QRect(100, 240, 221, 71))
        self.pushButton_start_nav2.setStyleSheet(
            "QPushButton {\n"
            "    /* Base Appearance */\n"
            "    background-color: #cccccc; /* Changed to Light Grey */\n"
            "    color: #333333; /* Changed text color to dark grey for contrast */\n"
            "    border: 1px solid #999999; /* Darker border for definition */\n"
            "    border-radius: 4px; \n"
            "    padding: 6px 12px; \n"
            "    \n"
            "    /* Font and Symbol Styling */\n"
            "    font-family: Arial, sans-serif; \n"
            "    font-size: 12pt; \n"
            "    font-weight: bold;\n"
            "}"
        )
        self.pushButton_start_nav2.setObjectName("pushButton_start_nav2")
        self.labelownRobi_2 = QtWidgets.QLabel(self.frame_2)
        self.labelownRobi_2.setGeometry(QtCore.QRect(20, 70, 181, 16))
        self.labelownRobi_2.setObjectName("labelownRobi_2")
        self.comboBox_mode_select = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_mode_select.setGeometry(QtCore.QRect(20, 90, 191, 61))
        self.comboBox_mode_select.setObjectName("comboBox_mode_select")
        self.label_battery = QtWidgets.QLabel(self.tab_3)
        self.label_battery.setGeometry(QtCore.QRect(10, 790, 111, 41))
        self.label_battery.setObjectName("label_battery")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(10, 780, 71, 16))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 884, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser_Overview.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                'li.unchecked::marker { content: "\\2610"; }\n'
                'li.checked::marker { content: "\\2612"; }\n'
                "</style></head><body style=\" font-family:'Ubuntu'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
                '<p align="center" style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'Sans Serif\'; font-size:12pt; font-weight:600;">Robot race Operating Procedures</span></p>\n'
                '<p align="center" style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Sans Serif\'; font-size:12pt; font-weight:600;"><br /></p>\n'
                "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Sans Serif'; font-size:11pt; font-weight:700;\">1. Robot selection: </span><span style=\" font-family:'Sans Serif'; font-size:11pt;\">Select the designated robot unit (Group 2 is 'Turtle 2').</span></p>\n"
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'Sans Serif\'; font-size:11pt; font-weight:700;">2. Opponent Selection: </span><span style=" font-family:\'Sans Serif\'; font-size:11pt;">Designate the opposing unit.</span></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'Sans Serif\'; font-size:11pt; font-weight:700;">3. Pose Initialization:</span><span style=" font-family:\'Sans Serif\'; font-size:11pt;"> Current location and orientation visible in RViz 2D Pose Estimation.</span></p>\n'
                "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Droid Sans Mono','monospace','monospace'; font-size:11pt; font-weight:700; color:#000000;\">4. Target Selection:</span><span style=\" font-family:'Droid Sans Mono','monospace','monospace'; font-size:11pt; color:#000000;\"> Set the destination by using the Nav2 Goal in RViz.</span></p>\n"
                "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Droid Sans Mono','monospace','monospace'; font-size:11pt; font-weight:700; color:#000000;\">5. Execution.</span></p></body></html>",
            )
        )
        self.labelownRobi.setText(_translate("MainWindow", "Robot"))
        self.start_pushButton.setText(_translate("MainWindow", "Execution"))
        self.checkBox_ManualMode.setText(_translate("MainWindow", "Teleoperation"))
        self.spoofing_checkBox.setText(_translate("MainWindow", "Spoofing"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Robot")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Logs")
        )
        self.manual_control.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:18pt; font-weight:700;">Manual Control</span></p></body></html>',
            )
        )
        self.pushButton_undock.setText(_translate("MainWindow", "Undock"))
        self.pushButton_dock.setText(_translate("MainWindow", "Dock"))
        self.pushButton_backw.setText(_translate("MainWindow", "Backw"))
        self.pushButton_right.setText(_translate("MainWindow", "Right"))
        self.pushButton_stopdrive.setText(_translate("MainWindow", "Stop"))
        self.pushButton_left.setText(_translate("MainWindow", "Left"))
        self.pushButton_fwd.setText(_translate("MainWindow", "Fwd"))
        self.Speed_Label.setText(_translate("MainWindow", "Speed"))
        self.pushButton_Stop.setText(_translate("MainWindow", "Emergency"))
        self.manual_control_3.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:18pt; font-weight:700;">Nav2 Control</span></p></body></html>',
            )
        )
        self.pushButton_stop_nav2.setText(_translate("MainWindow", "Stop Nav2 Viz"))
        self.pushButton_start_nav2.setText(_translate("MainWindow", "Start Nav2 Viz"))
        self.labelownRobi_2.setText(_translate("MainWindow", "Mode Selection"))
        self.label_battery.setText(_translate("MainWindow", "SOC:"))
        self.label.setText(_translate("MainWindow", "Akku in %"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Control")
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
