# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ws/src/sopias4_application/ui/second_final.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(884, 1284)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 20, 801, 951))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textBrowser_Overview = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_Overview.setGeometry(QtCore.QRect(30, 10, 721, 241))
        self.textBrowser_Overview.setObjectName("textBrowser_Overview")
        self.comboBox_ownRobi = QtWidgets.QComboBox(self.tab)
        self.comboBox_ownRobi.setGeometry(QtCore.QRect(100, 530, 191, 61))
        self.comboBox_ownRobi.setObjectName("comboBox_ownRobi")
        self.comboBox_oppRobi = QtWidgets.QComboBox(self.tab)
        self.comboBox_oppRobi.setGeometry(QtCore.QRect(520, 530, 191, 61))
        self.comboBox_oppRobi.setObjectName("comboBox_oppRobi")
        self.labelownRobi = QtWidgets.QLabel(self.tab)
        self.labelownRobi.setGeometry(QtCore.QRect(100, 510, 181, 16))
        self.labelownRobi.setObjectName("labelownRobi")
        self.labeloppRobi = QtWidgets.QLabel(self.tab)
        self.labeloppRobi.setGeometry(QtCore.QRect(520, 510, 181, 16))
        self.labeloppRobi.setObjectName("labeloppRobi")
        self.start_pushButton = QtWidgets.QPushButton(self.tab)
        self.start_pushButton.setGeometry(QtCore.QRect(190, 660, 381, 161))
        self.start_pushButton.setObjectName("start_pushButton")
        self.error_textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.error_textBrowser.setGeometry(QtCore.QRect(50, 840, 641, 51))
        self.error_textBrowser.setObjectName("error_textBrowser")
        self.checkBox_ManualMode = QtWidgets.QCheckBox(self.tab)
        self.checkBox_ManualMode.setGeometry(QtCore.QRect(590, 800, 121, 21))
        self.checkBox_ManualMode.setObjectName("checkBox_ManualMode")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textEdit_log = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_log.setGeometry(QtCore.QRect(20, 40, 751, 851))
        self.textEdit_log.setObjectName("textEdit_log")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_right = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_right.setGeometry(QtCore.QRect(410, 220, 80, 23))
        self.pushButton_right.setObjectName("pushButton_right")
        self.horizontalSlider_velo = QtWidgets.QSlider(self.tab_3)
        self.horizontalSlider_velo.setGeometry(QtCore.QRect(160, 360, 381, 71))
        self.horizontalSlider_velo.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_velo.setObjectName("horizontalSlider_velo")
        self.pushButton_left = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_left.setGeometry(QtCore.QRect(190, 220, 80, 23))
        self.pushButton_left.setObjectName("pushButton_left")
        self.Speed_Label = QtWidgets.QLabel(self.tab_3)
        self.Speed_Label.setGeometry(QtCore.QRect(320, 360, 57, 15))
        self.Speed_Label.setObjectName("Speed_Label")
        self.pushButton_fwd = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_fwd.setGeometry(QtCore.QRect(300, 170, 80, 23))
        self.pushButton_fwd.setObjectName("pushButton_fwd")
        self.pushButton_backw = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_backw.setGeometry(QtCore.QRect(300, 280, 80, 23))
        self.pushButton_backw.setObjectName("pushButton_backw")
        self.pushButton_stopdrive = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_stopdrive.setGeometry(QtCore.QRect(300, 220, 80, 23))
        self.pushButton_stopdrive.setObjectName("pushButton_stopdrive")
        self.pushButton_undock = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_undock.setGeometry(QtCore.QRect(490, 10, 101, 71))
        self.pushButton_undock.setObjectName("pushButton_undock")
        self.pushButton_dock = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_dock.setGeometry(QtCore.QRect(600, 10, 111, 71))
        self.pushButton_dock.setObjectName("pushButton_dock")
        self.pushButton_stop_nav2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_stop_nav2.setGeometry(QtCore.QRect(490, 90, 101, 71))
        self.pushButton_stop_nav2.setObjectName("pushButton_stop_nav2")
        self.pushButton_start_nav2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_start_nav2.setGeometry(QtCore.QRect(600, 90, 111, 71))
        self.pushButton_start_nav2.setObjectName("pushButton_start_nav2")
        self.tabWidget.addTab(self.tab_3, "")
        self.label_battery = QtWidgets.QLabel(self.centralwidget)
        self.label_battery.setGeometry(QtCore.QRect(40, 1140, 111, 41))
        self.label_battery.setObjectName("label_battery")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 1130, 71, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 884, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser_Overview.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Willkommen zum Robo Rennen. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">So gehts:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">1. Eigenen Roboter auswählen, (Gruppe 1 hat Turtle1)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">2. Gegner Auswählen</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">3. A</span><span style=\" font-family:\'Droid Sans Mono\',\'monospace\',\'monospace\'; font-size:11pt; color:#000000;\">ktuelle Lage des Roboters über RviZ 2D Pose Estimation</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans Mono\',\'monospace\',\'monospace\'; font-size:11pt; color:#000000;\">4. Ziel des Roboters über RviZ Nav2 Goal wählen</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans Mono\',\'monospace\',\'monospace\'; font-size:11pt; color:#000000;\">5. Starten!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt; color:#000000;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans Mono\',\'monospace\',\'monospace\'; font-size:11pt; color:#000000;\">6. Zuschauen und Spaß haben :)</span></p></body></html>"))
        self.labelownRobi.setText(_translate("MainWindow", "Eigener Roboter"))
        self.labeloppRobi.setText(_translate("MainWindow", "Gegnerischer Roboter"))
        self.start_pushButton.setText(_translate("MainWindow", "Start"))
        self.checkBox_ManualMode.setText(_translate("MainWindow", "ManuellerModus"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.pushButton_right.setText(_translate("MainWindow", "Right"))
        self.pushButton_left.setText(_translate("MainWindow", "Left"))
        self.Speed_Label.setText(_translate("MainWindow", "Speed"))
        self.pushButton_fwd.setText(_translate("MainWindow", "Fwd"))
        self.pushButton_backw.setText(_translate("MainWindow", "Backw"))
        self.pushButton_stopdrive.setText(_translate("MainWindow", "Stop"))
        self.pushButton_undock.setText(_translate("MainWindow", "Undock"))
        self.pushButton_dock.setText(_translate("MainWindow", "Dock"))
        self.pushButton_stop_nav2.setText(_translate("MainWindow", "stopp_nav2"))
        self.pushButton_start_nav2.setText(_translate("MainWindow", "start_nav2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
        self.label_battery.setText(_translate("MainWindow", "SOC:"))
        self.label.setText(_translate("MainWindow", "Akku in %"))
